# Generated by Django 5.2.11 on 2026-05-06 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('location', models.CharField(max_length=200, verbose_name='店铺地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='店铺简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='salons/', verbose_name='店铺图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
