# Generated by Django 5.2.11 on 2026-05-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('specialty', models.CharField(max_length=100, verbose_name='专业技能')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='services.salon', verbose_name='所属店铺')),
            ],
        ),
    ]
