# Generated by Django 5.2.11 on 2026-05-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('price_range', models.CharField(max_length=50, verbose_name='Price Range')),
                ('duration', models.IntegerField(help_text='Estimated duration (minutes)', verbose_name='Duration')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.salon', verbose_name='Salon')),
            ],
        ),
    ]
