# Generated by Django 5.2.11 on 2026-05-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, default='General Stylist', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='专业技能'),
        ),
    ]
