# Generated by Django 5.2.11 on 2026-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_staff_role_alter_staff_phone_alter_staff_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
