# Generated by Django 5.2.11 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_staff_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_range',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=30, help_text='Average duration in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='price_note',
            field=models.CharField(blank=True, default='Price varies by age and hair length/style.', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Services'),
        ),
    ]
