# Generated by Django 5.2.11 on 2026-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Phone Number'),
        ),
    ]
