# Generated by Django 5.2.11 on 2026-05-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_salon_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile Picture'),
        ),
    ]
