# Generated by Django 5.2.11 on 2026-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/', verbose_name='Photo'),
        ),
    ]
