# Generated by Django 5.2.11 on 2026-05-14 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salon',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/', verbose_name='Salon Image'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Salon Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=30, help_text='Average duration in minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.salon', verbose_name='Salon'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='services.salon', verbose_name='Salon'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialty'),
        ),
    ]
