# Generated by Django 5.2.11 on 2026-06-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_salonreview_staffreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='business_hours',
            field=models.CharField(default='10:00 AM - 07:00 PM', max_length=100, verbose_name='Business Hours'),
        ),
    ]
