# Generated by Django 5.2.11 on 2026-06-30 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_salon_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=20, validators=[django.core.validators.RegexValidator(message='Contact number must be between 11 and 12 digits.', regex='^\\d{11,12}$')], verbose_name='Contact Number'),
        ),
    ]
